version: '3'
volumes:
    dados:
networks:
    banco:
    web:
    fila:
services: 
    db:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            # Data volume
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - banco
    frontend:
        image: nginx:1.13
        volumes:
            # website
            - ./web:/usr/share/nginx/html/
            # Reverse proxy config
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - web
        depends_on:
            - app
    app:
        image: python:3.6
        volumes:
            # Application
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        networks:
            - banco
            - web
            - fila
        depends_on:
            - db
            - queue
        environment: 
            - DB_NAME=email_sender
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=db
    queue:
        image: redis:3.2
        networks:
            - fila
        environment: 
            - REDIS_HOST=queue
    worker: 
        build: worker
        volumes:
            # Worker
            - ./worker:/worker
        working_dir: /worker
        command: worker.py
        networks:
            - fila
        depends_on: 
            - queue
    